# Generated by Django 4.1.3 on 2022-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registermodal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=110)),
                ("Mo_No", models.BigIntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.BigIntegerField()),
                ("image", models.ImageField(default="", upload_to="Profile_img")),
            ],
        ),
    ]
